workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 30
    environment:
      java: 11
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build APK
        script:gradle assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
